---
title: "Week 2 tasks"
author: "teodor dyakov"
date: "10/15/2020"
output:
  word_document: default
  html_document: default
  pdf_document: 
    latex_engine: lualatex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r week 2}
library(MASS)

#намираме първо всички стойности в колоната Smoke
unique(survey$Smoke)

#Задача 1
#вероятноста случайно избран човек да е редовен пушач
sum(survey$Smoke == 'Regul', na.rm = TRUE)/nrow(survey)

maleSmokers = sum(survey$Smoke == 'Regul' & survey$Sex == 'Male', na.rm = TRUE)

#вероятността случайно избран човек да е мъж и редовен пушач
maleSmokers/nrow(survey)

#броят на всички мъже
maleNumber = sum(survey$Sex == 'Male', na.rm = TRUE)

#вероятността случайно избран мъж да е редовен пушач
maleSmokers/maleNumber

#броят на всички редовни пушачи
regulCount = sum(survey$Smoke == 'Regul', na.rm = TRUE)

#вероятноста случайно избран редовен пушач да е мъж
maleSmokers/regulCount


#втори начин със позлване на prop.table()

#вероятността случайно избран човек да е редовен пушач
table = prop.table(table(survey$Smoke),)
table['Regul']

#вероятността случайно избран човек да е мъж и редовен пушач
table = prop.table(table(survey$Sex,survey$Smoke),)
table['Male', 'Regul']

#вероятносттa мъж да е редовен пушач
table = prop.table(table(survey$Sex,survey$Smoke), 1)
table['Male', 'Regul']

#вероятността редовен пушач да е мъж:
table = prop.table(table(survey$Sex,survey$Smoke), 2)
table['Male','Regul']

#Зад 2
#барплот на броя на типовете пушачи
barplot(table(survey$Smoke))

#пушене в зависимост от пола
table = prop.table(table(survey$Sex,survey$Smoke),)
barplot(table, legend.text = TRUE)

#Зад 3
#некви статистики
summary(survey$Height)
heightMean = mean(survey$Height, na.rm = TRUE)
heightSd = sd(survey$Height, na.rm = TRUE)


maleHeights = survey[survey$Sex == 'Male', 'Height']
summary(maleHeights)
sd(maleHeights, na.rm = TRUE)

femaleHeights = survey[survey$Sex == 'Female', 'Height']
summary(femaleHeights)
sd(femaleHeights, na.rm = TRUE)

#каква част от студентите се различават от ср. височина с <= 1 стандартно отклонение?
sum(abs(survey$Height - heightMean) <= heightSd, na.rm = TRUE)/sum(!is.na(survey$Height))

#Зад 4
hist(survey$Height, breaks = 20)

#Зад 5
#хистограма на пулса на студентите
hist(survey$Pulse, prob = TRUE)

#графика плътността на разпределението на пулса 
lines(density(survey$Pulse, na.rm = TRUE))

#Зад 6
group1 = survey[survey$Age < 20,]
group2 = survey[survey$Age >= 20 & survey$Age < 25,]
group3 = survey[survey$Age >= 25,]

pie(x = c(nrow(group1), nrow(group3), nrow(group3)), labels = c('< 20', '20-25', '> 25'), main = 'Age of students')

barplot(table(group1$Smoke), main = 'smoking habits, < 20 years')
barplot(table(group2$Smoke), main = 'smoking habits, 20-25 years')
barplot(table(group3$Smoke), main = 'smoking habits, > 25 years old')

```